### ISSUE TITLE
Tracked URL on iOS are showing as Device: Desktop

### ISSUE THREAD

**Issue by nmarkovic04** [Parsely/parsely-ios#10]
A couple of days ago, I implemented Parse.ly on our iOS app and everything worked fine. Today, we're noticing that all the tracked URL go under Device: Desktop instead of Mobile. Is this a known issue?

**Comment by emmettbutler** [comment]
Hi @nmarkovic04. Are you referring to the Device Breakdown section of the post page in Parse.ly? I'm currently not aware of an issue that causes mobile SDK views to be counted as desktop views. Please let us know where exactly you're seeing this issue - maybe a screenshot (with sensitive analytics data redacted) could help in this case. Thanks!

**Comment by nmarkovic04** [comment]
@emmett9001 Yep, device breakdown. I've set the filter to 'Today' for an old post.

Code:
`ParselyTracker.sharedInstanceWithApiKey("ourKey").trackURL(path)
  ParselyTracker.sharedInstanceWithApiKey("ourKey").flush()`

Output:
`<ParselyTracker.m:(51)> [Parsely] {
    data =     {
        appname = "Krazy Coupon Lady";
        idsite = "hidden";
        manufacturer = Apple;
        os = iOS;
        "os_version" = "10.0.1";
        "parsely_site_uuid" = e38777570ed6b3e19a02e8601c814af22fbce648;
        urlref = "parsely_mobile_sdk";
    };
    ts = "1476125660.873272";
    url = "http://thekrazycouponlady.com/2016/10/10/crest-3d-white-toothpaste-only-1-00-at-walgreens-starting-1016/";
}`

![screenshot](https://www.dropbox.com/s/bg8sqcvhy5390dt/ss_parsely.jpg?raw=1)

**Comment by emmettbutler** [comment]
@nmarkovic04 I actually can't verify the issue you're seeing. When I visit [the dashboard page](https://dash.parsely.com/thekrazycouponlady.com/posts/NBx0nu-crest-3d-white-toothpaste-only-1-00-at-walgreens-starting-10-16/?start=2016-10-10&end=2016-10-10) for the post in question, I see views coming from mobile, tablet, and desktop. Is it possible you were looking at this post immediately after it was published? Mobile SDK events can take a bit longer to arrive in the dashboard.

**Comment by nmarkovic04** [comment]
@emmett9001 I'm pretty sure I'm still seeing it. E.g. [the post I just tested](https://dash.parsely.com/thekrazycouponlady.com/posts/E3gXCF-skippy-peanut-butter-only-1-45-at-walgreens/?minutes=today) has one desktop view today and no mobile views. 

`<ParselyTracker.m:(51)> [Parsely] {
    data =     {
        appname = "Krazy Coupon Lady";
        idsite = "hidden";
        manufacturer = Apple;
        os = iOS;
        "os_version" = "10.0";
        "parsely_site_uuid" = 6e007cf8dbce855e582d8e2ca6ef96f2af6b0340;
        urlref = "parsely_mobile_sdk";
    };
    ts = "1476259990.545018";
    url = "http://thekrazycouponlady.com/2016/02/14/skippy-peanut-butter-only-1-45-at-walgreens/";
}`

**Comment by emmettbutler** [comment]
@nmarkovic04 I did a bit more digging here and have a likely cause. Here's the user agent on the event you sent to Parse.ly:

```
Krazy%20Coupon%20Lady/6 CFNetwork/808.0.2 Darwin/15.5.0
```

Our backend appends a marker to make the user agent this:

```
Krazy%20Coupon%20Lady/6 CFNetwork/808.0.2 Darwin/15.5.0 , Parsely mobileproxy
```

As you can see, the user agent string includes the string `Krazy%20Coupon%20Lady`. Parse.ly uses the [user-agents](https://pypi.python.org/pypi/user-agents) package to differentiate desktop, mobile, and tablet views. This interactive python output shows that the `user_agents` module can't differentiate this user agent from a desktop one:

``` python
In [2]: import user_agents
In [3]: agent = "Krazy%20Coupon%20Lady/6 CFNetwork/808.0.2 Darwin/15.5.0 , Parsely mobileproxy"
In [4]: user_agents.parse(agent).is_tablet
Out[4]: False
In [5]: user_agents.parse(agent).is_mobile
Out[5]: False
```

Can you include the default user agent in its entirety instead of overwriting part of it? I imagine doing so would let `user_agents` understand it better.

**Comment by nmarkovic04** [comment]
@emmett9001 We are not fiddling with the user agent. It's included in it's original form. The default user agent on iOS is "ProductName/BuildNumber CFNetwork/<version> Darwin/<version>" iirc.

> Can you include the default user agent in its entirety instead of overwriting part of it? I imagine doing so would let user_agents understand it better.

Not sure what you mean by 'overwriting part of it'.

> In [2]: import user_agents
> In [3]: agent = "Krazy%20Coupon%20Lady/6 CFNetwork/808.0.2 Darwin/15.5.0 , Parsely mobileproxy"
> In [4]: user_agents.parse(agent).is_tablet
> Out[4]: False
> In [5]: user_agents.parse(agent).is_mobile
> Out[5]: False

I see. The question is, how does it identify whether it's mobile(is_mobile)? Also, since the Parse.ly SDK is responsible for sending the request, the only way to change anything on our side would be to change the ParselyTracker.m file source which we didn't do.

**Comment by emmettbutler** [comment]
Thanks, in that case, this might actually be an issue with python's `user_agents` module. I'll take a closer look.

**Comment by emmettbutler** [comment]
@nmarkovic04 I've opened an issue and pull request on python's `user_agents` module that should address this.

**Comment by emmettbutler** [comment]
@nmarkovic04 A fix for this issue has been deployed to Parsely's data collection system. Let me know here if you're still seeing the problem. Thanks!
