### ISSUE TITLE
Use Reachability as pod dependency 

### ISSUE THREAD

**Issue by gholias** [Parsely/parsely-ios#13]
Right now your SDK has Reachability classes embed and that is causing conflicts in our project because we already use the Reachability pod.

It would be better if Reachability is handled as a dependency
http://guides.cocoapods.org/syntax/podspec.html#dependency

**Comment by cwisecarver** [comment]
Hey @gholias, thanks for your interest in our SDK. 

Lots of customers that use our SDK don’t use cocoapods and by removing our internal copy of Reachability in favor of installing it with pods we’d be forcing them to use pods or not get upgrades/fixes to our SDK. 

If you want to fork our repo and replace Reachability with the pods version that’s more than fine with us. We’d love to have a version that is more aligned with our customers that do use cocoapods.

**Comment by cwisecarver** [comment]
I forked our repo and made the requested changes. https://github.com/cwisecarver/parsely-ios

**Comment by emmettbutler** [comment]
@cwisecarver I know we probably talked about this already, but what's stopping us from making this change in the main repo?

**Comment by cwisecarver** [comment]
> Lots of customers that use our SDK don’t use cocoapods and by removing our internal copy of Reachability in favor of installing it with pods we’d be forcing them to use pods or not get upgrades/fixes to our SDK.
