### ISSUE TITLE
cocoapods podspec version

### ISSUE THREAD

**Issue by reinpk** [Parsely/parsely-ios#6]
https://github.com/Parsely/parsely-ios/releases has version 2.2 but podspec is at 1.0.4
https://github.com/Parsely/parsely-ios/blob/master/Parsely.podspec#L3

be sure to update this version number and repo as well:
https://github.com/Parsely/parsely-ios/blob/master/Parsely.podspec#L9

**Comment by jtotoole** [comment]
a belated update—closed via https://github.com/Parsely/parsely-ios/commit/008df2e33978ee11fd4f1d30b7231cc0ab97f954
