### ISSUE TITLE
question: what is the url for trackURL?

### ISSUE THREAD

**Issue by reinpk** [Parsely/parsely-ios#7]
seeing as apps don't really have urls, what should the url argument be? suppose you have a named screen like "Login" or even a screen for an article like "Justice Department drops lawsuit against Apple"... what would the url be?

**Comment by emmettbutler** [comment]
The `url` parameter is meant to be the canonical URL of the post corresponding to the post being viewed in the app. This assumes a mapping of app content to web content - any post I can view on the app can also be viewed on the web, and has a canonical URL there.

**Comment by reinpk** [comment]
gotcha, and a valid url parameter is required? could it be an event name if there's no web canonical version?

**Comment by emmettbutler** [comment]
A URL is always required, since Parse.ly doesn't do custom event tracking.
