### ISSUE TITLE
Segment integration

### ISSUE THREAD

**Issue by nmarkovic04** [Parsely/parsely-ios#9]
I'm trying to integrate parse.ly with Segment on iOS. I've enabled the parse.ly integration on the segment dashboard and added the library to project using cocoapods.
1. We're showing posts both on our website and in our iOS app. Is it possible to track URLs of these posts? I've used `ParselyTracker.sharedInstanceWithApiKey(ourKey).trackURL(URLString)`, but I didn't see any activity under the specific post.
2. Is there an ability to show debug information?
3. When Segment sends an event, under the debug data, parse.ly is not listed as an integration: `integrations =             {
               "Google Analytics" = 0;
           };`
   Should it be there?

Thanks in advance

**Comment by emmettbutler** [comment]
Hi @nmarkovic04, and thanks for checking out Parse.ly's SDK. Your tracking call looks correct - just make sure that the URL you're passing to the Parse.ly SDK exactly matches the canonical URL of the post you want it to match with in the dashboard. You can find the canonical URL by checking the page's metadata, formats for which are documented [here](http://www.parsely.com/help/integration/jsonld/).

The SDK does not currently include a facility for printing debug information. You may be able to get some helpful output by changing the `#define PLog` line in `ParselyTracker.h` to the following:

``` c++
#define PLog( s, ... ) NSLog( @"<%@:(%d)> [Parsely] %@", [[NSString stringWithUTF8String:__FILE__] lastPathComponent], __LINE__, [NSString stringWithFormat:(s), ##__VA_ARGS__] )
```

As for the Segment integration, I'll need to dig in a bit to figure out why Parse.ly isn't appearing in the `integrations` listing. The Segment/Parse.ly iOS integration is still in beta, and this is an issue that still has not been worked out.

**Comment by nmarkovic04** [comment]
You were right, the URL wasn't matching. Thanks, @emmett9001 .
